language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: compartetusideas-nodejs
  api_key:
    secure: jc7zEGhHOYYpOopXg7zFA2hrHdU1U/qAZD6ofMSrGmYWUqC84CxnOI2i7Mo0QxKif8G8+ZGPOFVsel5OfCKNfOw0S3Y18BS1v0KO4og9VE7UG2BJo/mQ6Ao2bw/mtrRZYVYtIEVI8yagKOarfY8M+GWPPFMlUpmtW07lH++t371hu4ElkoNLW1u+xVJYYwNl/mHZ5lS9pSObHKhhZ5VE0K/dlhhLtoboo49PttVBrPWFdhihbjKkpf0FzsftuQ3vYopAlHZUEQ1yzTfiw42bo5Giunn0vqLW2yDoPpy8D1jTw53SMtcuE9Xk39whg7ZbVnXQAmhUDVEtv+dIGmJBLBB+rr32Al3hlm28Ch8wgwVa7X8q9ATlmm0FmnDYnBVqbjEKinX0apTBWzFlrZBFFoXOIqZIP/+Y52tKQGGqJyWCnzDm7hT0qfrl9DE/SQkArjzp4Fps8jmqXWCt73LAikAOdPv1vzP6MJpBsiVNVjINVpuR8BwfX8rfLrlGXsFX3M0Rurhym0tCO0uyR/Ig54mZeofShOfg6Ce4v+ptmd7n+EpLq33GU+jLetzAfchE1jfppcyS5lsFcMKebPf+jL4TzJDaZxQYr4TL5TnYD2yL4YnmhjHjpf60cNNC7ygE4OVSaG/p1vRvPA/60uh8RUJaUxnCCiiwMSwO+qmXGdg=
 